# Generated by Django 4.0.3 on 2022-03-18 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_tag_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='tags',
            field=models.ManyToManyField(null=True, to='base.tag'),
        ),
    ]
