# Generated by Django 4.0.3 on 2022-03-18 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_tag_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='body',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
